### ISSUE TITLE
Simplify the CSS code for the font-weight property. 

### ISSUE THREAD

**Issue by josephtkim** [tj724/prj-rev-bwfs-dasmoto#5]
Good job simplifying the CSS code for the font-family property. The font-weight property is also shared by multiple selectors, so you can simplify the code further for this as well. Like so,

```css
h1, span {
  font-weight: bold;
}
```
